# http://trac.ffmpeg.org/wiki/CompilationGuide/Centos

  - name: get opus src
    git: repo=git://git.opus-codec.org/opus.git dest="{{ ffmpeg_sources }}/opus" accept_hostkey=yes

  - name: opus config steps
    command: chdir="{{ ffmpeg_sources }}/opus" {{ item }}
    with_items: 
      - 'autoreconf -fiv'
      - './configure --prefix="{{ ffmpeg_build }}" --disable-shared'
   
  - name: run make for opus
    shell: chdir="{{ ffmpeg_sources }}/opus" {{ item }} 
    with_items:
      - 'make'
      - 'make install'
      - 'make distclean'
