# http://trac.ffmpeg.org/wiki/CompilationGuide/Centos

  - name: get libvorbis-1.3.4 src
    unarchive: src=libvorbis-1.3.4.tar.gz dest="{{ ffmpeg_sources }}"

  - name: libvorbis-1.3.4 config steps
    command: chdir="{{ ffmpeg_sources }}/libvorbis-1.3.4" {{ item }}
    with_items: 
      - './configure --prefix="{{ ffmpeg_build }}" --with-ogg="{{ ffmpeg_build }}" --disable-shared'
   
  - name: run make for libvorbis-1.3.4
    shell: chdir="{{ ffmpeg_sources }}/libvorbis-1.3.4" {{ item }} 
    with_items:
      - 'make'
      - 'make install'
      - 'make distclean'
