---

  - name: install java
    yum: name=java-1.7.0-openjdk state=latest 

  - name: is jetty config'd?
    stat: path={{ APP_PATH }}/jetty
    register: jetty_dir

  - name: install jetty with solr and fedora
    command: chdir={{ APP_PATH }} bundle exec rake jetty:clean
    when: jetty_dir.stat.exists == false

  - name: configure jetty with solr and fedora
    command: chdir={{ APP_PATH }} bundle exec rake sufia:jetty:config
    when: jetty_dir.stat.exists == false
    ignore_errors: True #bug from change of fedora directory

  - name: start jetty (with Solr and Fedora)
    command: chdir={{ APP_PATH }} bundle exec rake jetty:start
    ignore_errors: True #most of the time stderr doesn't mean it isn't running
